export const CAPITEMS_LIST_REQUEST = 'CAPITEMS_LIST_REQUEST'
export const CAPITEMS_LIST_SUCCESS = 'CAPITEMS_LIST_SUCCESS'
export const CAPITEMS_LIST_FAIL = 'CAPITEMS_LIST_FAIL'

export const CAPITEMS_DETAILS_REQUEST = 'CAPITEMS_DETAILS_REQUEST'
export const CAPITEMS_DETAILS_SUCCESS = 'CAPITEMS_DETAILS_SUCCESS'
export const CAPITEMS_DETAILS_FAIL = 'CAPITEMS_DETAILS_FAIL'
