export const FOOTWEARITEMS_LIST_REQUEST = 'FOOTWEARITEMS_LIST_REQUEST'
export const FOOTWEARITEMS_LIST_SUCCESS = 'FOOTWEARITEMS_LIST_SUCCESS'
export const FOOTWEARITEMS_LIST_FAIL = 'FOOTWEARITEMS_LIST_FAIL'

export const FOOTWEARITEMS_DETAILS_REQUEST = 'FOOTWEARITEMS_DETAILS_REQUEST'
export const FOOTWEARITEMS_DETAILS_SUCCESS = 'FOOTWEARITEMS_DETAILS_SUCCESS'
export const FOOTWEARITEMS_DETAILS_FAIL = 'FOOTWEARITEMS_DETAILS_FAIL'
