export const FOOTWEARITEMS_LIST_REQUEST = 'FOOTWEARITEMS_LIST_REQUEST'
export const FOOTWEARITEMS_LIST_SUCCESS = 'FOOTWEARITEMS_LIST_SUCCESS'
export const FOOTWEARITEMS_LIST_FAIL = 'FOOTWEARITEMS_LIST_FAIL'
