export const HOODIEITEMS_LIST_REQUEST = 'HOODIEITEMS_LIST_REQUEST'
export const HOODIEITEMS_LIST_SUCCESS = 'HOODIEITEMS_LIST_SUCCESS'
export const HOODIEITEMS_LIST_FAIL = 'HOODIEITEMS_LIST_FAIL'

export const HOODIEITEMS_DETAILS_REQUEST = 'HOODIEITEMS_DETAILS_REQUEST'
export const HOODIEITEMS_DETAILS_SUCCESS = 'HOODIEITEMS_DETAILS_SUCCESS'
export const HOODIEITEMS_DETAILS_FAIL = 'HOODIEITEMS_DETAILS_FAIL'
