export const KNITWEARITEMS_LIST_REQUEST = 'KNITWEARITEMS_LIST_REQUEST'
export const KNITWEARITEMS_LIST_SUCCESS = 'KNITWEARITEMS_LIST_SUCCESS'
export const KNITWEARITEMS_LIST_FAIL = 'KNITWEARITEMS_LIST_FAIL'

export const KNITWEARITEMS_DETAILS_REQUEST = 'KNITWEARITEMS_DETAILS_REQUEST'
export const KNITWEARITEMS_DETAILS_SUCCESS = 'KNITWEARITEMS_DETAILS_SUCCESS'
export const KNITWEARITEMS_DETAILS_FAIL = 'KNITWEARITEMS_DETAILS_FAIL'
