export const KNITWEARITEMS_LIST_REQUEST = 'KNITWEARITEMS_LIST_REQUEST'
export const KNITWEARITEMS_LIST_SUCCESS = 'KNITWEARITEMS_LIST_SUCCESS'
export const KNITWEARITEMS_LIST_FAIL = 'KNITWEARITEMS_LIST_FAIL'
