export const PANTITEMS_LIST_REQUEST = 'PANTITEMS_LIST_REQUEST'
export const PANTITEMS_LIST_SUCCESS = 'PANTITEMS_LIST_SUCCESS'
export const PANTITEMS_LIST_FAIL = 'PANTITEMS_LIST_FAIL'

export const PANTITEMS_DETAILS_REQUEST = 'PANTITEMS_DETAILS_REQUEST'
export const PANTITEMS_DETAILS_SUCCESS = 'PANTITEMS_DETAILS_SUCCESS'
export const PANTITEMS_DETAILS_FAIL = 'PANTITEMS_DETAILS_FAIL'
