export const SETITEMS_LIST_REQUEST = 'SETITEMS_LIST_REQUEST'
export const SETITEMS_LIST_SUCCESS = 'SETITEMS_LIST_SUCCESS'
export const SETITEMS_LIST_FAIL = 'SETITEMS_LIST_FAIL'

export const SETITEMS_DETAILS_REQUEST = 'SETITEMS_DETAILS_REQUEST'
export const SETITEMS_DETAILS_SUCCESS = 'SETITEMS_DETAILS_SUCCESS'
export const SETITEMS_DETAILS_FAIL = 'SETITEMS_DETAILS_FAIL'
