export const SHORTITEMS_LIST_REQUEST = 'SHORTITEMS_LIST_REQUEST'
export const SHORTITEMS_LIST_SUCCESS = 'SHORTITEMS_LIST_SUCCESS'
export const SHORTITEMS_LIST_FAIL = 'SHORTITEMS_LIST_FAIL'

export const SHORTITEMS_DETAILS_REQUEST = 'SHORTITEMS_DETAILS_REQUEST'
export const SHORTITEMS_DETAILS_SUCCESS = 'SHORTITEMS_DETAILS_SUCCESS'
export const SHORTITEMS_DETAILS_FAIL = 'SHORTITEMS_DETAILS_FAIL'
