export const TEEITEMS_LIST_REQUEST = 'TEEITEMS_LIST_REQUEST'
export const TEEITEMS_LIST_SUCCESS = 'TEEITEMS_LIST_SUCCESS'
export const TEEITEMS_LIST_FAIL = 'TEEITEMS_LIST_FAIL'

export const TEEITEMS_DETAILS_REQUEST = 'TEEITEMS_DETAILS_REQUEST'
export const TEEITEMS_DETAILS_SUCCESS = 'TEEITEMS_DETAILS_SUCCESS'
export const TEEITEMS_DETAILS_FAIL = 'TEEITEMS_DETAILS_FAIL'
