export const TSHIRTITEMS_LIST_REQUEST = 'TSHIRTITEMS_LIST_REQUEST'
export const TSHIRTITEMS_LIST_SUCCESS = 'TSHIRTITEMS_LIST_SUCCESS'
export const TSHIRTITEMS_LIST_FAIL = 'TSHIRTITEMS_LIST_FAIL'

export const TSHIRTITEMS_DETAILS_REQUEST = 'TSHIRTITEMS_DETAILS_REQUEST'
export const TSHIRTITEMS_DETAILS_SUCCESS = 'TSHIRTITEMS_DETAILS_SUCCESS'
export const TSHIRTITEMS_DETAILS_FAIL = 'TSHIRTITEMS_DETAILS_FAIL'
