export const products_0 = [
  {
    _id: '1',
    name: 'Vintage Harajuku sweatshirt-Women',
    image: '/tees_images/IMG_0914.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Sweatshirt',
    price: 9000,
    countInStock: 32,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '1',
    name: 'Vintage Harajuku sweatshirt-Women',
    image: '/sweatshirt_images/IMG_0924.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Sweatshirt',
    price: 9000,
    countInStock: 32,
    rating: 4.5,
    numReviews: 12,
  },
]
export const shirtItems = [
  {
    _id: '1',
    name: 'Smile graphics T-Shirt',
    image: '/tshirt_images/IMG_0764.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 9000,
    countInStock: 32,
  },
  {
    _id: '2',
    name: 'Mens short-sleeve equilibrum T-shirt',
    image: '/images/phone.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small ',
    category: 'Tees',
    price: 7000,
    countInStock: 27,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Guys letter Tee',
    image: '/images/camera.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small ',
    brand: 'Cannon',
    category: 'Tees',
    price: 8500,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Men cactus & letter graphic tee',
    image: '/images/playstation.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Vintage cherub graphic tee',
    image: '/images/mouse.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: '',
    category: 'Please choose one size up as these run small',
    price: 7500,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Rabbit embroidery tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small ',
    category: 'Tees',
    price: 8500,
    countInStock: 20,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Unisex oversized tee distorted portrait',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 17,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Rabbit embroidery tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 15,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Men astronaut & letter graphic tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 25,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Athletic heather "like Adults" tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 23,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Forward print cotton tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 9,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Washed alphabet prit tee - Black',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
]
export const footwearItems = [
  {
    _id: '1',
    name: "Men's Mesh Casual Sneakers",
    image: '/footwear_images/IMG_0817.JPG',
    category: 'Footwear',
    price: '23,000',
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Canvas Sneaker',
    image: '/footwear_images/IMG_1944.JPG',
    category: 'Footwear',
    price: '36,000',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Air Jordan 1',
    image: '/footwear_images/IMG_1943.JPG',
    brand: 'Cannon',
    category: 'Footwear',
    price: '57,000',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Wild Sand Knit Runner',
    image: '/footwear_images/IMG_0820.JPG',
    price: '27,500',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: "Men's Nike Air Barrage",
    image: '/footwear_images/IMG_0821.JPG',
    category: 'Footwear',
    price: '37,000',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: "Nike Air Mag 'Grey Mag'",
    image: '/footwear_images/IMG_0823.JPG',
    category: 'Footwear',
    price: '45,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: "Air More Uptempo 'Black White'",
    image: '/footwear_images/IMG_0824.JPG',
    category: 'Footwear',
    price: '65,300',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Trainers Sneakers Shoe',
    image: '/footwear_images/IMG_0825.JPG',
    category: 'Footwear',
    price: '30,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Lace Up Chunky Shoes',
    image: '/footwear_images/IMG_0826.JPG',
    category: 'Footwear',
    price: '22,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Versace Black Leather Sandals',
    image: '/footwear_images/IMG_0827.JPG',
    category: 'Footwear',
    price: '19,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Arizona Soft Slide Sandal',
    image: '/footwear_images/IMG_0828.JPG',
    category: 'Footwear',
    price: '13,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Lightweight Casual Shoes',
    image: '/footwear_images/IMG_0818.JPG',
    category: 'Footwear',
    price: '20,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Custom Nike Airforce 1',
    image: '/footwear_images/IMG_1946.JPG',
    category: 'Footwear',
    price: '33,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Barklay Canvas Plain Toe Oxford',
    image: '/footwear_images/IMG_1949.JPG',
    category: 'Footwear',
    price: '22,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '15',
    name: 'Non-Slip EVA Flip Flops',
    image: '/footwear_images/IMG_1951.JPG',
    category: 'Footwear',
    price: '17,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const knitwearItems = [
  {
    _id: '1',
    name: 'Vintage Knitwear',
    image: '/knitwear_images/IMG_1952.JPG',
    category: 'Knitwears',
    price: '17,000',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Knitwear Item',
    image: '/knitwear_images/IMG_1953.JPG',
    category: 'Knitwears',
    price: '13,000',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Knitted Cardigan',
    image: '/knitwear_images/IMG_1954.JPG',
    category: 'Knitwears',
    price: '25,000',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Knitted Sweater',
    image: '/knitwear_images/IMG_1956.JPG',
    category: 'Knitwears',
    price: '25,200',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Knitted Sweater',
    image: '/knitwear_images/IMG_1957.JPG',
    category: 'Knitwears',
    price: '12,000',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Knitted Cardigan',
    image: '/knitwear_images/IMG_1959.JPG',
    category: 'Knitwears',
    price: '13,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Fancy Knitted Sweater',
    image: '/knitwear_images/IMG_1960.JPG',
    category: 'Knitwears',
    price: '15,300',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Knitted Sweater',
    image: '/knitwear_images/IMG_1961.JPG',
    category: 'Knitwears',
    price: '20,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Knitted Cardigan',
    image: '/knitwear_images/IMG_1962.JPG',
    category: 'Knitwears',
    price: '15,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const hoodiesItems = [
  {
    _id: '1',
    name: 'Winter Fleece Anime Sweatshirt',
    image: '/hoodies_images/IMG_0829.JPG',
    category: 'Hoodies',
    price: '17,000',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Layered Hoodie',
    image: '/hoodies_images/IMG_0830.JPG',
    category: 'Hoodies',
    price: '13,000',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Black Nylon Color Block Hoodie',
    image: '/hoodies_images/IMG_0831.JPG',
    category: 'Hoodies',
    price: '15,000',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'White Hoodie',
    image: '/hoodies_images/IMG_0832.JPG',
    category: 'Hoodies',
    price: '15,200',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'White Hoodie With Rose Design',
    image: '/hoodies_images/IMG_0833.JPG',
    category: 'Hoodies',
    price: '12,000',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Black Grey Hoodie',
    image: '/hoodies_images/IMG_0834.JPG',
    category: 'Hoodies',
    price: '13,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Green Fancy Hoodie',
    image: '/hoodies_images/IMG_0835.JPG',
    category: 'Hoodies',
    price: '15,300',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Purple With Black Hoodie Sweatshirt',
    image: '/hoodies_images/IMG_0836.JPG',
    category: 'Hoodies',
    price: '20,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Black Hoodie With Red Rose Design',
    image: '/hoodies_images/IMG_0837.JPG',
    category: 'Hoodies',
    price: '15,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: "Men's Crazy Patch Detail With White Hoodie",
    image: '/hoodies_images/IMG_0838.JPG',
    category: 'Hoodies',
    price: '15,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: "Men's Designer Hoodie",
    image: '/hoodies_images/IMG_0839.JPG',
    category: 'Hoodies',
    price: '15,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: "Fancy Men's Designer Hoodie",
    image: '/hoodies_images/IMG_0840.JPG',
    category: 'Hoodies',
    price: '15,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Essentials Hoodie Sweatshirt',
    image: '/hoodies_images/IMG_0841.JPG',
    category: 'Hoodies',
    price: '15,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const capItems = [
  {
    _id: '1',
    name: 'Brown Baseball Cap',
    image: '/cap_images/IMG_0829.JPG',
    category: 'Cap',
    price: '7,000',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'City Of Angels A-Frame Snapback',
    image: '/cap_images/IMG_0830.JPG',
    category: 'Cap',
    price: '3,000',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Letter Embroidered Baseball Cap',
    image: '/cap_images/IMG_0831.JPG',
    category: 'Cap',
    price: '5,000',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: "Men's NY Yankees Cap",
    image: '/cap_images/IMG_0832.JPG',
    category: 'Cap',
    price: '5,200',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'LA Snapback Baseball Cap',
    image: '/cap_images/IMG_0833.JPG',
    category: 'Cap',
    price: '2,000',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Black Grey Hoodie',
    image: '/cap_images/IMG_0834.JPG',
    category: 'Cap',
    price: '3,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Green Fancy Hoodie',
    image: '/cap_images/IMG_0835.JPG',
    category: 'Cap',
    price: '5,300',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Purple With Black Hoodie Sweatshirt',
    image: '/cap_images/IMG_0836.JPG',
    category: 'Cap',
    price: '3,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Black Hoodie With Red Rose Design',
    image: '/cap_images/IMG_0837.JPG',
    category: 'Cap',
    price: '5,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: "Men's Crazy Patch Detail With White Hoodie",
    image: '/cap_images/IMG_0838.JPG',
    category: 'Cap',
    price: '15,100',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: "Men's Designer Hoodie",
    image: '/cap_images/IMG_0839.JPG',
    category: 'Cap',
    price: '5,000',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: "Fancy Men's Designer Hoodie",
    image: '/cap_images/IMG_0840.JPG',
    category: 'Cap',
    price: '5,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Essentials Hoodie Sweatshirt',
    image: '/cap_images/IMG_0841.JPG',
    category: 'Cap',
    price: '6,500',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
