export const products_0 = [
  {
    _id: '1',
    name: 'Vintage Harajuku sweatshirt-Women',
    image: '/tees_images/IMG_0914.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Sweatshirt',
    price: 9000,
    countInStock: 32,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '1',
    name: 'Vintage Harajuku sweatshirt-Women',
    image: '/sweatshirt_images/IMG_0924.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Sweatshirt',
    price: 9000,
    countInStock: 32,
    rating: 4.5,
    numReviews: 12,
  },
]
export const capItems = [
  {
    _id: '1',
    name: 'Smile graphics T-Shirt',
    image: '/tshirt_images/IMG_0764.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 9000,
    countInStock: 32,
  },
  {
    _id: '2',
    name: 'Mens short-sleeve equilibrum T-shirt',
    image: '/images/phone.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small ',
    category: 'Tees',
    price: 7000,
    countInStock: 27,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Guys letter Tee',
    image: '/images/camera.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small ',
    brand: 'Cannon',
    category: 'Tees',
    price: 8500,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Men cactus & letter graphic tee',
    image: '/images/playstation.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Vintage cherub graphic tee',
    image: '/images/mouse.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: '',
    category: 'Please choose one size up as these run small',
    price: 7500,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Rabbit embroidery tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small ',
    category: 'Tees',
    price: 8500,
    countInStock: 20,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Unisex oversized tee distorted portrait',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 17,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Rabbit embroidery tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 15,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Men astronaut & letter graphic tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 25,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Athletic heather "like Adults" tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 23,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Forward print cotton tee',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 9,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Washed alphabet prit tee - Black',
    image: '/images/alexa.jpg',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    price: 8500,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
]
export const footwearItems = [
  {
    _id: '1',
    name: 'Sneakers with green laceing',
    image: '/footwear_images/IMG_0817.JPG',
    category: 'Footwear',
    price: 23000,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Black Canvas',
    image: '/footwear_images/IMG_0818.JPG',
    category: 'Footwear',
    price: 20000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Black and White sneakers',
    image: '/footwear_images/IMG_0819.JPG',
    brand: 'Cannon',
    category: 'Footwear',
    price: 25000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Combat Sneakers design',
    image: '/footwear_images/IMG_0820.JPG',
    price: 25200,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'White and Black intertwine',
    image: '/footwear_images/IMG_0821.JPG',
    category: 'Footwear',
    price: 31000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Grey and black with white sole',
    image: '/footwear_images/IMG_0823.JPG',
    category: 'Footwear',
    price: 32000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Air Jordans',
    image: '/footwear_images/IMG_0824.JPG',
    category: 'Footwear',
    price: 45300,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'All white Sneakers',
    image: '/footwear_images/IMG_0825.JPG',
    category: 'Footwear',
    price: 24000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Classic Sneakers',
    image: '/footwear_images/IMG_0826.JPG',
    category: 'Footwear',
    price: 32100,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Classic Versace palms',
    image: '/footwear_images/IMG_0827.JPG',
    category: 'Footwear',
    price: 15000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Brown Sole palm',
    image: '/footwear_images/IMG_0828.JPG',
    category: 'Footwear',
    price: 13500,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const products_3 = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const products_4 = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const products_5 = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const products_6 = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
